EMS/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView

from organization.api.views import OrganizationCreateAPIView
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("", views.HomePage.as_view(), name='home'),
    path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
    path("api/schema/docs/", SpectacularSwaggerView.as_view(url_name="schema")),
    path('api/login/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path("api/signup/", OrganizationCreateAPIView.as_view(), name="signup"),
    path("api/admin/<slug:org_slug>/",
         include("organization.api.urls", namespace="org_api")),
    path("api/staff/<slug:org_slug>/",
         include("staff.api.urls", namespace="staff_api")),
    path('ems/<slug:org_slug>/dashboard/admin/', include('organization.urls')),
    path('ems/<slug:org_slug>/dashboard/staff/', include('staff.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)




accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views
from .forms import LoginForm

app_name = 'accounts'

urlpatterns = [
    path("login/", auth_views.LoginView.as_view(template_name="accounts/login.html", authentication_form = LoginForm),name='login'),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("signup/", views.SignUp.as_view(), name="signup"),
    path('password_reset/', views.CustomPasswordReset.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

accounts/models.py
from django.contrib.auth.models import PermissionsMixin, AbstractUser, UserManager
from django.db import models
# from phonenumber_field.modelfields import PhoneNumberField
# Create your models here.

class MyUserManager(UserManager):
    
    def create_org_admin(self, username, email, password, **extra_fields):
        """creates admin user"""
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", False)

        return self.create_user(username, email, password, **extra_fields)
    
    def create_superuser(self, username, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")

        return self.create_user(username, email, password, **extra_fields)

class User(AbstractUser, PermissionsMixin):
    """Custom user model """
    email = models.EmailField(verbose_name = "email address", max_length=255, unique=True)
    
    objects = MyUserManager()
    
        


accounts/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm


class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control form-control-lg', 'id': 'username', 'placeholder': 'Enter Username'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control form-control-lg', 'id': 'password', 'placeholder': 'Enter Password'}))


accounts/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView
from .models import User
from django.contrib.auth import views as auth_views

from organization.forms import OrganizationSignUpForm

# Create your views here.
class SignUp(CreateView):
    form_class = OrganizationSignUpForm
    success_url = reverse_lazy("accounts:login")
    template_name = "accounts/signup.html"

    def form_valid(self, form):
        organization = form.save(commit=False)
        # create a new user and assign it to the admin field
        admin = User.objects.create_org_admin(
            username=form.cleaned_data['admin_username'],
            email=form.cleaned_data["admin_email"],
            password=form.cleaned_data['password1'],
            first_name=form.cleaned_data["admin_fname"],
            last_name=form.cleaned_data["admin_lname"],
        )
        organization.admin = admin
        organization.save()
        return super().form_valid(form)
    
    
class CustomPasswordReset(auth_views.PasswordResetView):
    success_url = reverse_lazy("accounts:password_reset_done")

accounts/templates/accounts/login.html
{% extends 'base_login.html' %}

{% block login-content %}
<h4>Hello! let's get started</h4>
<h6 class="font-weight-light">Sign in to continue.</h6>

<form method="POST" class="pt-3">
  {% csrf_token %}

  <div class="form-group">
      {{ form.username }}
  </div>

  <div class="form-group">
      {{ form.password }}
  </div>

  <div class="mt-3">
    <input class="btn btn-block btn-primary btn-lg font-weight-medium auth-form-btn" value="LOGIN" type="submit">
  </div>

  <div class="my-2 d-flex justify-content-between align-items-center">
    <a href="{% url 'accounts:password_reset' %}" class="auth-link text-black">Forgot password?</a>
  </div>

  <div class="text-center mt-4 font-weight-light">
    Don't have an account? Sign your organization up here! <a href="{% url 'accounts:signup' %}" class="text-primary">Sign Up</a>
  </div>
</form>

{% endblock %}

accounts/templates/accounts/signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Skydash Admin</title>
  <!-- plugins:css -->
  <link rel="stylesheet" href="{% static 'vendors/feather/feather.css' %}">
  <link rel="stylesheet" href="{% static 'vendors/ti-icons/css/themify-icons.css' %}">
  <link rel="stylesheet" href="{% static 'vendors/css/vendor.bundle.base.css' %}">
  <!-- endinject -->
  <!-- Plugin css for this page -->
  <!-- End plugin css for this page -->
  <!-- inject:css -->
  <link rel="stylesheet" href="{% static 'css/vertical-layout-light/style.css' %}">
  <!-- endinject -->
  <link rel="shortcut icon" href="{% static 'images/favicon.png' %}" />
</head>

<body>
  <div class="container-scroller">
    <div class="container-fluid page-body-wrapper full-page-wrapper">
      <div class="content-wrapper d-flex align-items-center auth px-0">
        <div class="row w-100 mx-0">
          <div class="col-lg-4 mx-auto">
            <div class="auth-form-light text-left py-5 px-4 px-sm-5">
              <div class="brand-logo">
                <img src="{% static 'images/logo.svg' %}" alt="logo">
              </div>
              <h4>New here?</h4>
              <h6 class="font-weight-light">Signing up is easy. It only takes a few steps</h6>


              <form method="POST" class="pt-3">
                {% csrf_token %}
                {% if form.errors %}
                  <div class="alert alert-danger">
                    <strong>Oops! There was an error:</strong>
                    <ul>
                      {% for field, error in form.errors.items %}
                        {% if field != NON_FIELD_ERRORS %}
                          <li>{{ field }}: {{ error }}</li>
                        {% else %}
                          <li>{{ error }}</li>
                        {% endif %}
                      {% endfor %}
                    </ul>
                  </div>
                {% endif %}
                <div class="form-group">
                  {{ form.name.label_tag }}
                  {{ form.name }}
                </div>

                <div class="form-group">
                    {{ form.address.label_tag }}
                    {{ form.address }}
                </div>

                <div class="form-group">
                    {{ form.company_email_domain.label_tag }}
                    {{ form.company_email_domain }}
                </div>

                <div class="form-group">
                    {{ form.admin_fname.label_tag }}
                    {{ form.admin_fname }}
                </div>

                <div class="form-group">
                    {{ form.admin_lname.label_tag }}
                    {{ form.admin_lname }}
                </div>

                <div class="form-group">
                    {{ form.admin_username.label_tag }}
                    {{ form.admin_username }}
                </div>

                <div class="form-group">
                    {{ form.admin_email.label_tag }}
                    {{ form.admin_email }}
                </div>

                <div class="form-group">
                    {{ form.admin_phone_number.label_tag }}
                    {{ form.admin_phone_number }}
                </div>

                <div class="form-group">
                    {{ form.password1.label_tag }}
                    {{ form.password1 }}
                </div>

                <div class="form-group">
                    {{ form.password2.label_tag }}
                    {{ form.password2 }}
                </div>

                <div class="mb-4">
                  <div class="form-check">
                    <label class="form-check-label text-muted">
                      <input type="checkbox" class="form-check-input">
                      I agree to all Terms & Conditions
                    </label>
                  </div>
                </div>
                <div class="mt-3">
                  <input class="btn btn-block btn-primary btn-lg font-weight-medium auth-form-btn" value="Sign up" type="submit">
                </div>

                <div class="text-center mt-4 font-weight-light">
                  Already have an account? <a href="{% url 'accounts:login' %}" class="text-primary">Login</a>
                </div>

              </form>

            </div>
          </div>
        </div>
      </div>
      <!-- content-wrapper ends -->
    </div>
    <!-- page-body-wrapper ends -->
  </div>
  <!-- container-scroller -->
  <!-- plugins:js -->
  <script src="{% static 'vendors/js/vendor.bundle.base.js' %}"></script>
  <!-- endinject -->
  <!-- Plugin js for this page -->
  <!-- End plugin js for this page -->
  <!-- inject:js -->
  <script src="{% static 'js/off-canvas.js' %}"></script>
  <script src="{% static 'js/hoverable-collapse.js' %}"></script>
  <script src="{% static 'js/template.js' %}"></script>
  <script src="{% static 'js/settings.js' %}"></script>
  <script src="{% static 'js/todolist.js' %}"></script>
  <!-- endinject -->
</body>

</html>