EMS/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView

from organization.api.views import OrganizationCreateAPIView
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("", views.HomePage.as_view(), name='home'),
    path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
    path("api/schema/docs/", SpectacularSwaggerView.as_view(url_name="schema")),
    path('api/login/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path("api/signup/", OrganizationCreateAPIView.as_view(), name="signup"),
    path("api/admin/<slug:org_slug>/",
         include("organization.api.urls", namespace="org_api")),
    path("api/staff/<slug:org_slug>/",
         include("staff.api.urls", namespace="staff_api")),
    path('ems/<slug:org_slug>/dashboard/admin/', include('organization.urls')),
    path('ems/<slug:org_slug>/dashboard/staff/', include('staff.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)




organization/api/urls.py
from django.urls import path
from . import views

app_name = "org_api"
urlpatterns = [
    path("", views.OrganizationDetailAPIView.as_view(), name="organization-detail"),
    path("update/", views.OrganizationUpdateAPIView.as_view(), name="organization-update"),
    path("departments/", views.DepartmentListCreateAPIView.as_view(), name="dept_list_create"),
    path("departments/<int:pk>/", views.DepartmentDetailUpdateAPIView.as_view(), name="department-detail"),
    path("jobtitles/", views.JobTitleListCreateAPIView.as_view(), name="job_title_list_create"),
    path("jobtitles/<int:pk>/", views.JobTitleDetailUpdateDeleteAPIView.as_view(), name="job-title-detail"),
    path("staffs/", views.StaffListCreateAPIView.as_view(), name="staff_list_create"),
    path("staffs/csv/", views.StaffCreateFromCSVAPIView.as_view(), name="staff_create_from_csv"),
    path("staffs/<int:pk>/", views.StaffDetailUpdateAPIView.as_view(), name="staff-detail"),
    path("queries/", views.QueryListCreateAPIView.as_view(), name="query_list_create"),
    path("queries/<int:pk>/", views.QueryViewResponseAPIView.as_view(), name="query-detail"),
]


organization/urls.py
from django.urls import include, path
from . import views

app_name = 'organization'

urlpatterns = [
    path('', views.AdminDashboardView.as_view(), name='admin_dashboard'),
    path('<int:pk>/', views.OrgDetailView.as_view(), name='org_detail'),
    path('<int:pk>/update/', views.OrgUpdateView.as_view(), name='org_update'),
    path('staff/create/', views.StaffCreateChoiceView.as_view(), name='staff_create'),
    path('staff/create/csv/', views.CreateStaffFromCSV.as_view(), name='staff_create_csv'),
    path('staff/create/form/', views.StaffCreateFormView.as_view(), name='staff_create_form'),
    path('staff/<int:pk>/', views.StaffDetailView.as_view(), name="staff_detail"),
    path('staff/<int:pk>/update/', views.StaffUpdateView.as_view(), name="staff_update"),
    path('staff/<int:pk>/status_update/', views.StaffStatusUpdateView.as_view(), name='status_update_form'),
    path('departments/', views.DepartmentListView.as_view(), name="department_list"),
    path('departments/create/', views.DepartmentCreateView.as_view(), name="dept_create"),
    path('departments/<int:pk>/update', views.DepartmentUpdateView.as_view(), name="dept_update"),
    path('jobtitles/', views.JobTitleListView.as_view(), name="job_title_list"),
    path('jobtitles/create/', views.JobTitleCreateView.as_view(), name="job_title_create"),
    path('jobtitles/<int:pk>/update/', views.JobtTitleUpdateView.as_view(), name="job_title_update"),
    path('queries/', views.QueryListView.as_view(), name="query_list"),
    path('queries/create/', views.QueryCreateView.as_view(), name="query_create"),
    path('queries/<int:pk>/response/', views.QueryResponseView.as_view(), name="query_response"),
]

staff/models.py
from accounts.models import User
from django.db import models
from django.urls import reverse
from organization.models import Department, JobTitle, NigerianPhoneNumberField, Organization


# Create your models here.
class Query(models.Model):
    staff = models.ForeignKey('Staff', on_delete=models.SET_NULL, related_name="queries", null=True)
    query_requester = models.ForeignKey('Staff', on_delete=models.SET_NULL, null=True)
    reason = models.TextField()
    response = models.TextField(blank=True, null=True)
    organization = models.ForeignKey(Organization, on_delete=models.SET_NULL, related_name="queries", blank=True, null=True)
    is_responded = models.BooleanField(default=False)
    

    def __str__(self):
        return f'{self.staff} - {self.reason}'
    

class Staff(models.Model):
    
    STATE_CHOICES = [(state, state) for state in (
        'Abia', 'Adamawa', 'Akwa Ibom', 'Anambra', 'Bauchi', 'Bayelsa', 'Benue', 
        'Borno', 'Cross River', 'Delta', 'Ebonyi', 'Edo', 'Ekiti', 'Enugu', 'FCT',
        'Gombe', 'Imo', 'Jigawa', 'Kaduna', 'Kano', 'Katsina', 'Kebbi', 'Kogi', 
        'Kwara', 'Lagos', 'Nasarawa', 'Niger', 'Ogun', 'Ondo', 'Osun', 'Oyo', 
        'Plateau', 'Rivers', 'Sokoto', 'Taraba', 'Yobe', 'Zamfara'
    )]

    STAFF_STATUS = (
        ("Active", "Active"),
        ("On Leave", "On Leave"),
        ("Suspended", "Suspended"),
        ("Exited", "Exited"),
    )

    GENDER = (
        ("Male", "Male"),
        ("Female", "Female"),
    )

    user = models.OneToOneField(User, on_delete=models.SET_NULL, related_name="staff", null=True, blank=True)
    first_name = models.CharField(max_length=25)
    last_name = models.CharField(max_length=25)
    personal_email = models.EmailField()
    gender = models.CharField(max_length=10, choices=GENDER)
    work_email = models.EmailField(blank=True, null=True, unique=True)
    username = models.CharField(max_length=25, unique=True)
    phone_number = NigerianPhoneNumberField()
    date_of_birth = models.DateField()
    state_of_origin = models.CharField(max_length=25, choices=STATE_CHOICES)
    staff_status = models.CharField(max_length=10, choices=STAFF_STATUS, default="Active")
    next_of_kin_name = models.CharField(max_length=50)
    next_of_kin_email = models.EmailField()
    next_of_kin_phone_number = NigerianPhoneNumberField()
    dept = models.ForeignKey(Department, on_delete=models.SET_NULL, related_name="staffs",  blank=True, null=True)
    job_title = models.ForeignKey(JobTitle, on_delete=models.SET_NULL, related_name="staffs", blank=True, null=True)
    organization = models.ForeignKey(Organization, on_delete=models.SET_NULL, related_name="staffs", blank=True, null=True)
    date_employed = models.DateField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse("organization:staff_detail", kwargs={"pk": self.pk, "org_slug": self.organization.slug })

    def full_name(self):
        return f"{self.first_name} {self.last_name}"
    
    
    def __str__(self) -> str:
        return f"{self.first_name} {self.last_name}"
    

class UserProfile(models.Model):
    staff_profile = models.OneToOneField(Staff, on_delete=models.SET_NULL, related_name="userprofile", null=True, blank=True)
    profile_picture = models.ImageField(upload_to='profile_pictures/', blank=True, null=True)

    def __str__(self):
        return self.staff.first_name
    



organization/api/views.py
import csv
import random
import string

from django.conf import settings
from django.core.exceptions import ValidationError
from django.core.mail import send_mail
from django.db import transaction, IntegrityError
from django.shortcuts import get_object_or_404

from rest_framework import generics, status 
from rest_framework.permissions import IsAdminUser, IsAuthenticated
from rest_framework.response import Response 

from ..models import Department,Organization, JobTitle
from .serializers import OrganizationSerializer, DepartmentSerializer, JobTitleSerializer
from .permissions import IsPartOfOrg
from accounts.models import User
from staff.api.serializers import StaffSerializer, QuerySerializer
from staff.models import Staff, Query, UserProfile


class DepartmentListCreateAPIView(generics.ListCreateAPIView):
    serializer_class = DepartmentSerializer
    permission_classes = [IsAuthenticated, IsPartOfOrg, IsAdminUser]

    def perform_create(self, serializer):
        department = serializer.save(organization=self.request.user.organization)
        return department
    
    def get_queryset(self):
        return Department.objects.filter(organization=self.request.user.organization)
    

class DepartmentDetailUpdateAPIView(generics.RetrieveUpdateAPIView):
    serializer_class = DepartmentSerializer
    permission_classes = [IsAuthenticated, IsPartOfOrg, IsAdminUser]

    def get_queryset(self):
        return Department.objects.filter(organization=self.request.user.organization)
    
    def get_object(self):
        queryset = self.get_queryset()
        filter_kwargs = {
            'pk': self.kwargs['pk'],
        }
        obj = get_object_or_404(queryset, **filter_kwargs)
        self.check_object_permissions(self.request, obj)
        return obj


class JobTitleListCreateAPIView(generics.ListCreateAPIView):
    serializer_class = JobTitleSerializer
    permission_classes = [IsAuthenticated, IsPartOfOrg, IsAdminUser]

    def perform_create(self, serializer):
        dept_name = serializer.validated_data.pop('dept_name')
        department = get_object_or_404(Department, name__iexact=dept_name)
        job_title = serializer.save(organization=self.request.user.organization, department=department)
        job_title.save()
        return job_title
    
    def get_queryset(self):
        return JobTitle.objects.filter(organization=self.request.user.organization)
    
    
class JobTitleDetailUpdateDeleteAPIView(generics.RetrieveUpdateDestroyAPIView):
    serializer_class = JobTitleSerializer
    permission_classes = [IsAuthenticated, IsPartOfOrg, IsAdminUser]

    def get_queryset(self):
        return JobTitle.objects.filter(organization=self.request.user.organization)
    
    def get_object(self):
        queryset = self.get_queryset()
        filter_kwargs = {
            'pk': self.kwargs['pk'],
        }
        obj = get_object_or_404(queryset, **filter_kwargs)
        self.check_object_permissions(self.request, obj)
        return obj


class OrganizationCreateAPIView(generics.CreateAPIView):
    serializer_class = OrganizationSerializer

    def perform_create(self, serializer):
        user = User.objects.create_org_admin(username=serializer.validated_data['admin_username'],
                                            email=serializer.validated_data['admin_email'],
                                            password=serializer.validated_data['password1'],
                                            first_name=serializer.validated_data['admin_fname'],
                                            last_name=serializer.validated_data['admin_lname'],
        )
        validated_data = serializer.validated_data.copy()
        validated_data.pop('password1', None)
        validated_data.pop('password2', None)
        organization = serializer.Meta.model.objects.create(admin=user, **validated_data)
        serializer.instance = organization
        return organization


class OrganizationUpdateAPIView(generics.UpdateAPIView):
    serializer_class = OrganizationSerializer
    permission_classes = [IsAuthenticated, IsPartOfOrg, IsAdminUser]

    def get_object(self):
        return self.request.user.organization
    
class OrganizationDetailAPIView(generics.RetrieveAPIView):
    serializer_class = OrganizationSerializer
    permission_classes = [IsAuthenticated, IsPartOfOrg, IsAdminUser]

    def get_object(self):
        return self.request.user.organization


def generate_password(n=8):
    """Generate a random password of length n"""
    alphabet = string.ascii_letters + string.digits
    password = ''.join(random.choice(alphabet) for _ in range(n))
    return password


class StaffListCreateAPIView(generics.ListCreateAPIView):
    serializer_class = StaffSerializer
    permission_classes = [IsAuthenticated, IsPartOfOrg, IsAdminUser]

    def perform_create(self, serializer):
        current_org = self.request.user.organization
        staff = serializer.validated_data
        # Get Department Instance
        dept_name = staff.pop('dept_name')
        department = get_object_or_404(Department, name__iexact=dept_name)
        # Get Jobtitle instance
        job_title_role = staff.pop('job_title_role')
        job_title = get_object_or_404(JobTitle, role__iexact=job_title_role)
        # Generate work email
        work_email = f"{staff['first_name'][0].lower()}{staff['last_name'].lower()}@{current_org.company_email_domain}"
        # Generate password
        password = generate_password()
        print(f"Password for {staff['username']} is {password}")
        # Create Staff User and bind to Staff instance
        user = User.objects.create_user(username=staff['username'],
            email=work_email,
            password=password,
            first_name=staff['first_name'],
            last_name=staff['last_name'],
        )
        staff.user = user
        staff_instance = serializer.save(user=user, work_email=work_email, organization=current_org, dept=department, job_title=job_title)
        UserProfile.objects.create(staff_profile=staff_instance)
        return staff_instance
    
    def get_queryset(self):
        return Staff.objects.filter(organization=self.request.user.organization)
    
    
class StaffDetailUpdateAPIView(generics.RetrieveUpdateAPIView):
    serializer_class = StaffSerializer
    permission_classes = [IsAuthenticated, IsPartOfOrg, IsAdminUser]

    def get_queryset(self):
        return Staff.objects.filter(organization=self.request.user.organization)
    
    def get_object(self):
        queryset = self.get_queryset()
        filter_kwargs = {
            'pk': self.kwargs['pk'],
        }
        obj = get_object_or_404(queryset, **filter_kwargs)
        self.check_object_permissions(self.request, obj)
        return obj


class StaffCreateFromCSVAPIView(generics.CreateAPIView):
    serializer_class = StaffSerializer

    def post(self, request, *args, **kwargs):
        csv_file = request.data.get('file')
        current_org = request.user.organization
        if not csv_file:
             return Response({'error': 'No file uploaded.'}, status=status.HTTP_400_BAD_REQUEST)
        
        try:
            decoded_file = csv_file.read().decode('utf-8').splitlines()
            reader = csv.DictReader(decoded_file)
            with transaction.atomic():
                for row in reader:
                    try:
                        work_email = f"{row['first_name'][0].lower()}{row['last_name'].lower()}@{current_org.company_email_domain}"
                        password = generate_password()
                        print(f"{row['username']} : {password}")
                        user = User.objects.create_user(username=row['username'],
                                        email=work_email,
                                        password=password,
                                        first_name=row['first_name'],
                                        last_name=row['last_name'],
                                    )
                        serializer = self.get_serializer(data=row)
                        serializer.is_valid(raise_exception=True)
                        dept_name = serializer.validated_data.pop('dept_name')
                        department = get_object_or_404(Department, name__iexact=dept_name)
                        job_title_role = serializer.validated_data.pop('job_title_role')
                        job_title = get_object_or_404(JobTitle, role__iexact=job_title_role)
                        staff_instance = serializer.save(user=user, work_email=work_email, organization=current_org, dept=department, job_title=job_title)
                        UserProfile.objects.create(staff_profile=staff_instance)
                    except IntegrityError:
                        transaction.rollback()
                        return Response({{"Error": f"Error on row {reader.line_num}: Staff with username '{row['username']}' already exists."}})
        except csv.Error as e:
            return Response({"Error": f'Error processing CSV file: {e}'})
        
        subject = f"{current_org.name}: LOGIN CREDENTIALS"
        message = f"Dear {staff_instance.first_name},\n\nWelcome to {current_org.name}.\n\nLogin to your dashboard using these credentials.\n\nUsername: {staff_instance.username}\nPassword: {password}"
        recipient_list = [staff_instance.personal_email,]
        send_mail(subject, message, settings.EMAIL_HOST_USER, recipient_list)
        return Response(serializer.data, status=status.HTTP_201_CREATED)
            

class QueryListCreateAPIView(generics.ListCreateAPIView):
    serializer_class = QuerySerializer
    permission_classes = [IsAuthenticated, IsPartOfOrg, IsAdminUser]
    

organization/templates/organization/dashboard.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="content-wrapper">

    <div class="row">
      <div class="col-md-12 grid-margin">
        <div class="row">
          <div class="col-12 col-xl-8 mb-4 mb-xl-0">
            <h3 class="font-weight-bold">Welcome to your Admin Dashboard, {{user.organization.admin_fname}}</h3>
          </div>
        </div>
      </div>
    </div>


    <div class="row">

      <div class="col-md-6 grid-margin stretch-card">
        <div class="card card-tale">
          <div class="card-body d-flex justify-content-center align-items-center">
            <h1 class=" mb-2 display1"> <a style="color: inherit;" href="{{ user.organization.get_absolute_url }}">{{ user.organization.name }}</a></h1>
          </div>
        </div>
      </div>

      <div class="col-md-6 grid-margin transparent">

        <div class="row">

          <div class="col-md-6 mb-4 stretch-card transparent">
            <div class="card card-tale">
              <div class="card-body d-flex justify-content-center align-items-center">
                <p class="mb-4"></p>
                <p class="fs-30 mb-2"><a style="color: inherit;" href="{% url 'organization:staff_create' org_slug=user.organization.slug %}">Create Staff</a></p>
                <p></p>
              </div>
            </div>
          </div>

          <div class="col-md-6 mb-4 stretch-card transparent">
            <div class="card card-dark-blue">
              <div class="card-body d-flex justify-content-center align-items-center">
                <p class="mb-4"></p>
                <p class="fs-30 mb-2"><a style="color: inherit;" href="{% url "organization:department_list" org_slug=user.organization.slug %}">Departments</a></p>
                <p></p>
              </div>
            </div>
          </div>
        </div>

        <div class="row">

          <div class="col-md-6 mb-4 mb-lg-0 stretch-card transparent">
            <div class="card card-light-blue">
              <div class="card-body d-flex justify-content-center align-items-center">
                <p class="mb-4"></p>
                <p class="fs-30 mb-2"><a style="color: inherit;" href="{% url 'organization:job_title_list' org_slug=user.organization.slug %}">Job Titles</a></p>
                <p></p>
              </div>
            </div>
          </div>

          <div class="col-md-6 stretch-card transparent">
            <div class="card card-light-danger">
              <div class="card-body d-flex justify-content-center align-items-center">
                <p class="mb-4"></p>
                <p class="fs-30 mb-2"><a style="color: inherit;" href="{% url 'organization:query_list' org_slug=user.organization.slug %}">Queries</a></p>
                <p></p>
              </div>
            </div>
          </div>

        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-md grid-margin stretch-card">
        <div class="card">
          <div class="card-body">
            <p class="card-title mb-0">All Staff</p>
            <div class="table-responsive">
              <table class="table table-striped table-hover table-borderless">
                <thead>
                  <tr>
                    <th>Last Name</th>
                    <th>First Name</th>
                    <th>Work Email</th>
                    <th>Phone</th>
                    <th>Job Title</th>
                    <th>Department</th>
                    <th>Status</th>
                    <th>View</th>

                  </tr>  
                </thead>
                <tbody>
                  {% for staff in staff_list %}
                    <tr>
                      <td> {{ staff.last_name }} </td>
                      <td> {{ staff.first_name }} </td>
                      <td><span id="email-{{ staff.pk }}">{{ staff.work_email }}</span> </td>
                      <td><span id="phone-{{ staff.pk }}">{{ staff.phone_number }}</span></td>
                      <td> {{ staff.job_title.role }} </td>
                      <td> {{ staff.dept.name }} </td>
                      <td class="font-weight-medium"><a 
                        href="{% url 'organization:status_update_form' org_slug=user.organization.slug pk=staff.pk %}" 
                        class="badge {% if staff.staff_status == "Active" %}
                        badge-success
                        {% elif staff.staff_status == "Exited" %}
                        badge-danger
                        {% elif staff.staff_status == "Suspended" %}
                        badge-warning
                        {% else %}
                        badge-info
                        {% endif %}">
                        {{ staff.staff_status }}</a></td>
                      <td><a class="badge badge-primary" href="{{ staff.get_absolute_url }}">View</a></td>

                    </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>

  </div>

  
  <script>
    function copyToClipboard(text) {
      // Create a temporary input element
      const input = document.createElement('input');
      input.setAttribute('value', text);
      document.body.appendChild(input);
  
      // Select the text field
      input.select();
      input.setSelectionRange(0, 99999); // For mobile devices
  
      // Copy the text inside the text field
      document.execCommand('copy');
  
      // Remove the temporary input element
      document.body.removeChild(input);
    }
  
    // Add event listeners to email and phone number cells
    const emailCells = document.querySelectorAll('.table td:nth-child(3)');
    const phoneCells = document.querySelectorAll('.table td:nth-child(4)');
  
    emailCells.forEach(cell => {
      const email = cell.textContent;
      cell.innerHTML += ` <a href="#" class="copy-link" onclick="copyToClipboard('${email}')"><i class="mdi mdi-content-copy"></i></a>`;
    });
  
    phoneCells.forEach(cell => {
      const phone = cell.textContent;
      cell.innerHTML += ` <a href="#" class="copy-link" onclick="copyToClipboard('${phone}')"><i class="mdi mdi-content-copy"></i></a>`;
    });
  </script>
  

{% endblock %}

organization/templates/organization/department_form.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="content-wrapper">

  <div class="col-12 grid-margin stretch-card">
      <div class="card">
        <div class="card-body">
              <h4 class="card-title">Department Creation Form</h4>
              <p class="card-description">
                  Enter Details to create Department
              </p>
              <form method="POST" class="forms-sample">

                  {% csrf_token %}
                  {% if form.errors %}
                    <div class="alert alert-danger">
                      <strong>Oops! There was an error:</strong>
                      <ul>
                        {% for field, error in form.errors.items %}
                          {% if field != NON_FIELD_ERRORS %}
                            <li>{{ field }}: {{ error }}</li>
                          {% else %}
                            <li>{{ error }}</li>
                          {% endif %}
                        {% endfor %}
                      </ul>
                    </div>
                  {% endif %}

                  <div class="form-group">
                      {{ form.name.label_tag }}
                      {{ form.name }}
                  </div>
      
                  <div class="form-group">
                      {{ form.description.label_tag }}
                      {{ form.description }}
                  </div>

                  
                  <input class="btn btn-primary mr-2" value="Submit" type="submit">
                  <a href="{% url 'organization:admin_dashboard' org_slug=user.organization.slug %}" class="btn btn-danger">Cancel</a>

                  

              </form>
          </div>
      </div>
  </div>
</div>

{% endblock %}

organization/templates/organization/department_list.html
{% extends 'base.html' %}

{% block content %}
<div class="content-wrapper">
    <div class="row">
        <div class="col-md-12 grid-margin">
            <div class="row">
                <div class="col-12 col-xl-8 mb-4 mb-xl-0">
                    <h1>Departments</h1>
                </div>
            </div>
        </div>
    </div>
      

    <div>
        <ul>
            {% for dept in dept_list %}
        
            <li>
                <h3>{{ dept.name }}</h3>
                <p>{{ dept.description }}</p>
                <p><a class="btn btn-primary mr-2" href="{% url 'organization:dept_update' pk=dept.pk org_slug=user.organization.slug %}">Update</a></p>    
            </li>
            <br>
            {% endfor %}
        
        </ul>

        <a class="btn btn-success mr-2 mt-5" href="{% url 'organization:dept_create' org_slug=user.organization.slug %}"> Create New Department </a>
    </div>    
</div>


{% endblock%}

organization/templates/organization/job_title_form.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="content-wrapper">

  <div class="col-12 grid-margin stretch-card">
      <div class="card">
        <div class="card-body">
              <h4 class="card-title">Job Title Creation Form</h4>
              <p class="card-description">
                  Enter Details to create Job Title
              </p>
              <form method="POST" class="forms-sample">

                  {% csrf_token %}
                  {% if form.errors %}
                    <div class="alert alert-danger">
                      <strong>Oops! There was an error:</strong>
                      <ul>
                        {% for field, error in form.errors.items %}
                          {% if field != NON_FIELD_ERRORS %}
                            <li>{{ field }}: {{ error }}</li>
                          {% else %}
                            <li>{{ error }}</li>
                          {% endif %}
                        {% endfor %}
                      </ul>
                    </div>
                  {% endif %}

                  <div class="form-group">
                      {{ form.role.label_tag }}
                      {{ form.role }}
                  </div>
                  
                  <div class="form-group">
                    {{ form.department.label_tag }}
                    {{ form.department }}
                  </div>

                  <div class="form-group">
                      {{ form.description.label_tag }}
                      {{ form.description }}
                  </div>

                  
                  <input class="btn btn-primary mr-2" value="Submit" type="submit">
                  <a href="{% url 'organization:admin_dashboard' org_slug=user.organization.slug %}" class="btn btn-danger">Cancel</a>

              </form>
          </div>
      </div>
  </div>
</div>

{% endblock %}

organization/templates/organization/job_title_list.html
{% extends 'base.html' %}

{% block content %}
<div class="content-wrapper">

    <div class="row">
        <div class="col-md-12 grid-margin">
            <div class="row">
                <div class="col-12 col-xl-8 mb-4 mb-xl-0">
                    <h2>Job Titles</h2>
                </div>
            </div>
        </div>
    </div>

    <div>
        <ul>
            {% for job_title in job_title_list %}

            <li>
                <h3>{{ job_title.role }}</h3>
                <p class="text-primary">{{ job_title.department.name }}</p>
                <p>{{ job_title.description }}</p>
                <p><a class="btn btn-primary" href="{% url 'organization:job_title_update' org_slug=user.organization.slug pk=job_title.pk %}">Update</a></p>    
            </li>
            <br>
            {% endfor %}

        </ul>

        <a class="btn btn-success mr-2 mt-4" href="{% url 'organization:job_title_create' org_slug=user.organization.slug %}"> Create New Job Title </a>
    </div>
</div>
{% endblock%}

organization/templates/organization/query_list.html
{% extends 'base.html' %}

{% block content %}

<div class="content-wrapper">

    <div class="row">
        <div class="col-md-12 grid-margin">
            <div class="row">
                <div class="col-12 col-xl-8 mb-4 mb-xl-0">
                    <h2>All Queries</h2>
                </div>
            </div>
        </div>
    </div>

    <div> 
        <ul>
            {% for query in query_list %}

            <li>
                <p><strong>Query Reason:</strong> {{ query.reason }}</p>
                <p><strong>Query Recipient:</strong> {{ query.staff.full_name }}</p>
                <p><strong>Query Requester:</strong> {{ query.query_requester.full_name }}</p>
                {% if query.is_responded %}
                <p><a class="btn btn-primary" href="{% url 'organization:query_response' org_slug=user.organization.slug pk=query.pk %}">View Response</a></p>
                {% else%}
                <p class="text-danger">Not yet responded. </p>    
                {% endif %}
            </li>
            <br>
            {% empty %}
                <p>No Queries found.</p>
            {% endfor %}

        </ul>

        <a class="btn btn-success" href="{% url 'organization:query_create' org_slug=user.organization.slug %}"> Create New Query </a>
    </div>

</div>
{% endblock%}