EMS/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView

from organization.api.views import OrganizationCreateAPIView
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("", views.HomePage.as_view(), name='home'),
    path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
    path("api/schema/docs/", SpectacularSwaggerView.as_view(url_name="schema")),
    path('api/login/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path("api/signup/", OrganizationCreateAPIView.as_view(), name="signup"),
    path("api/admin/<slug:org_slug>/",
         include("organization.api.urls", namespace="org_api")),
    path("api/staff/<slug:org_slug>/",
         include("staff.api.urls", namespace="staff_api")),
    path('ems/<slug:org_slug>/dashboard/admin/', include('organization.urls')),
    path('ems/<slug:org_slug>/dashboard/staff/', include('staff.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)




accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views
from .forms import LoginForm

app_name = 'accounts'

urlpatterns = [
    path("login/", auth_views.LoginView.as_view(template_name="accounts/login.html", authentication_form = LoginForm),name='login'),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("signup/", views.SignUp.as_view(), name="signup"),
    path('password_reset/', views.CustomPasswordReset.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

organization/urls.py
from django.urls import include, path
from . import views

app_name = 'organization'

urlpatterns = [
    path('', views.AdminDashboardView.as_view(), name='admin_dashboard'),
    path('<int:pk>/', views.OrgDetailView.as_view(), name='org_detail'),
    path('<int:pk>/update/', views.OrgUpdateView.as_view(), name='org_update'),
    path('staff/create/', views.StaffCreateChoiceView.as_view(), name='staff_create'),
    path('staff/create/csv/', views.CreateStaffFromCSV.as_view(), name='staff_create_csv'),
    path('staff/create/form/', views.StaffCreateFormView.as_view(), name='staff_create_form'),
    path('staff/<int:pk>/', views.StaffDetailView.as_view(), name="staff_detail"),
    path('staff/<int:pk>/update/', views.StaffUpdateView.as_view(), name="staff_update"),
    path('staff/<int:pk>/status_update/', views.StaffStatusUpdateView.as_view(), name='status_update_form'),
    path('departments/', views.DepartmentListView.as_view(), name="department_list"),
    path('departments/create/', views.DepartmentCreateView.as_view(), name="dept_create"),
    path('departments/<int:pk>/update', views.DepartmentUpdateView.as_view(), name="dept_update"),
    path('jobtitles/', views.JobTitleListView.as_view(), name="job_title_list"),
    path('jobtitles/create/', views.JobTitleCreateView.as_view(), name="job_title_create"),
    path('jobtitles/<int:pk>/update/', views.JobtTitleUpdateView.as_view(), name="job_title_update"),
    path('queries/', views.QueryListView.as_view(), name="query_list"),
    path('queries/create/', views.QueryCreateView.as_view(), name="query_create"),
    path('queries/<int:pk>/response/', views.QueryResponseView.as_view(), name="query_response"),
]

staff/urls.py
from django.urls import path
from . import views

app_name = 'staff'

urlpatterns = [
    path("", views.StaffDashboardView.as_view(), name="staff_dashboard"),
    path("profile/", views.StaffProfileView.as_view(), name="staff_profile"),
    path("profile/upload_photo/", views.UploadProfilePictureView.as_view(), name="upload_photo"),
    path("queries/", views.StaffQueryListView.as_view(), name="query_list"),
    path("queries/<int:pk>/respond", views.StaffQueryResponseView.as_view(), name="query_response"),

]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>MAESTRO EMS</title>
  <!-- plugins:css -->
  <link rel="stylesheet" href="{% static 'vendors/feather/feather.css' %}">
  <link rel="stylesheet" href="{% static 'vendors/ti-icons/css/themify-icons.css' %}">
  <link rel="stylesheet" href="{% static 'vendors/css/vendor.bundle.base.css' %}">
  <link rel="stylesheet" href="{% static 'vendors/mdi/css/materialdesignicons.min.css' %}">
  <!-- Plugin css for this page -->
  <link rel="stylesheet" href="{% static 'vendors/datatables.net-bs4/dataTables.bootstrap4.css' %}">
  <link rel="stylesheet" href="{% static 'vendors/ti-icons/css/themify-icons.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'js/select.dataTables.min.css' %}">
  <!-- End plugin css for this page -->
  <!-- inject:css -->
  <link rel="stylesheet" href="{% static 'css/vertical-layout-light/style.css' %}">
  <!-- endinject -->
  <link rel="shortcut icon" href="{% static 'images/favicon.png' %}" />
</head>
<body>
    <style>
      .messages.vanish {
        opacity: 0;
        transition: opacity 0.5s ease-out;
      }
    </style>
    <div class="container-scroller">
      <!-- partial:partials/_navbar.html -->
      <nav class="navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
        <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center">
          {% if user.is_authenticated and user.is_staff %}
          <a class="navbar-brand brand-logo mr-5" href="{% url 'organization:admin_dashboard' org_slug=user.organization.slug %}"><img src="{% static 'images/logo.svg' %}" class="mr-2" alt="logo"/></a>
          <a class="navbar-brand brand-logo-mini" href="{% url 'organization:admin_dashboard' org_slug=user.organization.slug %}"><img src="{% static 'images/logo-mini.svg' %}" alt="logo"/></a>
          {% elif user.is_authenticated %}
          <a class="navbar-brand brand-logo mr-5" href="{% url 'staff:staff_dashboard' org_slug=user.staff.organization.slug %}"><img src="{% static 'images/logo.svg' %}" class="mr-2" alt="logo"/></a>
          <a class="navbar-brand brand-logo-mini" href="{% url 'staff:staff_dashboard' org_slug=user.staff.organization.slug %}"><img src="{% static 'images/logo-mini.svg' %}" alt="logo"/></a>
          {% endif%}
        </div>

        <div class="navbar-menu-wrapper d-flex align-items-center justify-content-end">
          <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
            <span class="icon-menu"></span>
          </button>

          <ul class="navbar-nav navbar-nav-right">
            <li class="nav-item">
              {% if user.is_authenticated %}
                <p class="mb-0 font-weight-normal float-left"><a class="nav-link" href="{% url 'accounts:logout' %}">
                  <i class="mdi mdi-logout"></i>
                  Logout<a></p>
              {% else %}
                <p><a class="nav-link" href="{% url 'accounts:login' %}">Login<a></p>  
              {% endif %}
            </li>
            
            <li class="nav-item nav-profile dropdown">
              <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" id="profileDropdown">
                <img src="{% static 'images/logo-mini.svg' %}" alt="profile"/>
              </a>
              <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="profileDropdown">
                <a class="dropdown-item">
                  <i class="ti-settings text-primary"></i>
                  Settings
                </a>
                {% if user.is_authenticated %}
                <a class="dropdown-item" href="{% url 'accounts:logout' %}">
                  <i class="mdi mdi-logout"></i>
                  Logout
                </a>
                {% endif %}
              </div>
            </li>
          </ul>
          <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
            <span class="icon-menu"></span>
          </button>
        </div>
      </nav>

      <div class="container-fluid page-body-wrapper">
        <nav class="sidebar sidebar-offcanvas" id="sidebar">
            <ul class="nav">
              <li class="nav-item">
                {% if user.is_authenticated and user.is_staff %}
                <a class="nav-link" href="{% url 'organization:admin_dashboard' org_slug=user.organization.slug %}">
                  <i class="icon-grid menu-icon"></i>
                  <span class="menu-title">Dashboard</span>
                </a>
                {% elif user.is_authenticated %}
                <a class="nav-link" href="{% url 'staff:staff_dashboard' org_slug=user.staff.organization.slug %}">
                  <i class="icon-grid menu-icon"></i>
                  <span class="menu-title">Dashboard</span>
                </a>
                {% endif %}
                  
              </li>
            </ul>
          </nav>
        <div class="main-panel">
          {% if messages %}
          <div class="messages">
              {% for message in messages %}
                  <div class="alert alert-{{ message.tags }}">
                      {{ message }}
                  </div>
              {% endfor %}
          </div>
          {% endif %}

          {% if user.is_authenticated %}

                {% block content %}

                {% endblock %}

          {% else%}
              <h1>Access Denied.</h1>
          {% endif %}

            <footer class="footer">
                <div class="d-sm-flex justify-content-center justify-content-sm-between">
                  <span class="text-muted text-center text-sm-left d-block d-sm-inline-block">Copyright © 2021.  Premium <a href="https://www.bootstrapdash.com/" target="_blank">Bootstrap admin template</a> from BootstrapDash. All rights reserved.</span>
                  <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Hand-crafted & made with <i class="ti-heart text-danger ml-1"></i></span>
                </div>
            </footer>
          </div>
      <!-- main-panel ends -->

      </div>
    <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->
    <script>
      const messages = document.querySelectorAll('.messages');

      // Remove each message after 5 seconds
      messages.forEach(message => {
        setTimeout(() => {
            message.classList.add('vanish');
          }, 5000);
          });
    </script>
      
    <!-- plugins:js -->
    <script src="{% static 'vendors/js/vendor.bundle.base.js' %}"></script>
    <!-- endinject -->
    <!-- Plugin js for this page -->
    <script src="{% static 'js/dataTables.select.min.js' %}"></script>

    <!-- End plugin js for this page -->
    <!-- inject:js -->
    <script src="{% static 'js/template.js' %}"></script>
    <!-- endinject -->
    <!-- Custom js for this page-->
    <script src="{% static 'js/dashboard.js' %}"></script>
    <!-- End custom js for this page-->
</body>

</html>

templates/base_login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Skydash Admin</title>
  <!-- plugins:css -->
  <link rel="stylesheet" href="{% static 'vendors/feather/feather.css' %}">
  <link rel="stylesheet" href="{% static 'vendors/ti-icons/css/themify-icons.css' %}">
  <link rel="stylesheet" href="{% static 'vendors/css/vendor.bundle.base.css' %}">
  <!-- endinject -->
  <!-- Plugin css for this page -->
  <!-- End plugin css for this page -->
  <!-- inject:css -->
  <link rel="stylesheet" href="{% static 'css/vertical-layout-light/style.css' %}">
  <!-- endinject -->
  <link rel="shortcut icon" href="{% static 'images/favicon.png' %}" />
</head>

<body>
  <div class="container-scroller">
    <div class="container-fluid page-body-wrapper full-page-wrapper">
      <div class="content-wrapper d-flex align-items-center auth px-0">
        <div class="row w-100 mx-0">
          <div class="col-lg-4 mx-auto">
            <div class="auth-form-light text-left py-5 px-4 px-sm-5">
              <div class="brand-logo">
                <img src="{% static 'images/logo.svg'%}" alt="logo">
              </div>
              
              {% block login-content %}

              
              {% endblock%}
              
            </div>
        </div>
      </div>
    </div>
    <!-- content-wrapper ends -->
  </div>
  <!-- page-body-wrapper ends -->
</div>
<!-- container-scroller -->
<!-- plugins:js -->
<script src="{% static 'vendors/js/vendor.bundle.base.js' %}"></script>
<!-- endinject -->
<!-- Plugin js for this page -->
<!-- End plugin js for this page -->
<!-- inject:js -->
<script src="{% static 'js/off-canvas.js' %}"></script>
<script src="{% static 'js/hoverable-collapse.js' %}"></script>
<script src="{% static 'js/template.js' %}"></script>
<script src="{% static 'js/settings.js' %}"></script>
<script src="{% static 'js/todolist.js' %}"></script>
<!-- endinject -->
</body>

</html>