EMS/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView

from organization.api.views import OrganizationCreateAPIView
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("", views.HomePage.as_view(), name='home'),
    path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
    path("api/schema/docs/", SpectacularSwaggerView.as_view(url_name="schema")),
    path('api/login/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path("api/signup/", OrganizationCreateAPIView.as_view(), name="signup"),
    path("api/admin/<slug:org_slug>/",
         include("organization.api.urls", namespace="org_api")),
    path("api/staff/<slug:org_slug>/",
         include("staff.api.urls", namespace="staff_api")),
    path('ems/<slug:org_slug>/dashboard/admin/', include('organization.urls')),
    path('ems/<slug:org_slug>/dashboard/staff/', include('staff.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)




staff/api/urls.py
from django.urls import path
from . import views

app_name = "staff_api"

urlpatterns = [
    path("staffs/", views.StaffListView.as_view(), name="staff_list"),
    path("queries/", views.CurrentStaffQueriesListAPIView.as_view(), name="query_list"),
    path("queries/<int:pk>/", views.QueryUpdateResponse.as_view(), name="query_response"),
    path("profile/", views.StaffUserProfileDetailAPIView.as_view(), name="staff_profile"),
    path("profile/upload/", views.StaffPictureUploadAPIView.as_view(), name="picture_upload"),
]

staff/urls.py
from django.urls import path
from . import views

app_name = 'staff'

urlpatterns = [
    path("", views.StaffDashboardView.as_view(), name="staff_dashboard"),
    path("profile/", views.StaffProfileView.as_view(), name="staff_profile"),
    path("profile/upload_photo/", views.UploadProfilePictureView.as_view(), name="upload_photo"),
    path("queries/", views.StaffQueryListView.as_view(), name="query_list"),
    path("queries/<int:pk>/respond", views.StaffQueryResponseView.as_view(), name="query_response"),

]

staff/models.py
from accounts.models import User
from django.db import models
from django.urls import reverse
from organization.models import Department, JobTitle, NigerianPhoneNumberField, Organization


# Create your models here.
class Query(models.Model):
    staff = models.ForeignKey('Staff', on_delete=models.SET_NULL, related_name="queries", null=True)
    query_requester = models.ForeignKey('Staff', on_delete=models.SET_NULL, null=True)
    reason = models.TextField()
    response = models.TextField(blank=True, null=True)
    organization = models.ForeignKey(Organization, on_delete=models.SET_NULL, related_name="queries", blank=True, null=True)
    is_responded = models.BooleanField(default=False)
    

    def __str__(self):
        return f'{self.staff} - {self.reason}'
    

class Staff(models.Model):
    
    STATE_CHOICES = [(state, state) for state in (
        'Abia', 'Adamawa', 'Akwa Ibom', 'Anambra', 'Bauchi', 'Bayelsa', 'Benue', 
        'Borno', 'Cross River', 'Delta', 'Ebonyi', 'Edo', 'Ekiti', 'Enugu', 'FCT',
        'Gombe', 'Imo', 'Jigawa', 'Kaduna', 'Kano', 'Katsina', 'Kebbi', 'Kogi', 
        'Kwara', 'Lagos', 'Nasarawa', 'Niger', 'Ogun', 'Ondo', 'Osun', 'Oyo', 
        'Plateau', 'Rivers', 'Sokoto', 'Taraba', 'Yobe', 'Zamfara'
    )]

    STAFF_STATUS = (
        ("Active", "Active"),
        ("On Leave", "On Leave"),
        ("Suspended", "Suspended"),
        ("Exited", "Exited"),
    )

    GENDER = (
        ("Male", "Male"),
        ("Female", "Female"),
    )

    user = models.OneToOneField(User, on_delete=models.SET_NULL, related_name="staff", null=True, blank=True)
    first_name = models.CharField(max_length=25)
    last_name = models.CharField(max_length=25)
    personal_email = models.EmailField()
    gender = models.CharField(max_length=10, choices=GENDER)
    work_email = models.EmailField(blank=True, null=True, unique=True)
    username = models.CharField(max_length=25, unique=True)
    phone_number = NigerianPhoneNumberField()
    date_of_birth = models.DateField()
    state_of_origin = models.CharField(max_length=25, choices=STATE_CHOICES)
    staff_status = models.CharField(max_length=10, choices=STAFF_STATUS, default="Active")
    next_of_kin_name = models.CharField(max_length=50)
    next_of_kin_email = models.EmailField()
    next_of_kin_phone_number = NigerianPhoneNumberField()
    dept = models.ForeignKey(Department, on_delete=models.SET_NULL, related_name="staffs",  blank=True, null=True)
    job_title = models.ForeignKey(JobTitle, on_delete=models.SET_NULL, related_name="staffs", blank=True, null=True)
    organization = models.ForeignKey(Organization, on_delete=models.SET_NULL, related_name="staffs", blank=True, null=True)
    date_employed = models.DateField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse("organization:staff_detail", kwargs={"pk": self.pk, "org_slug": self.organization.slug })

    def full_name(self):
        return f"{self.first_name} {self.last_name}"
    
    
    def __str__(self) -> str:
        return f"{self.first_name} {self.last_name}"
    

class UserProfile(models.Model):
    staff_profile = models.OneToOneField(Staff, on_delete=models.SET_NULL, related_name="userprofile", null=True, blank=True)
    profile_picture = models.ImageField(upload_to='profile_pictures/', blank=True, null=True)

    def __str__(self):
        return self.staff.first_name
    



staff/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import Query

class ProfilePictureForm(forms.Form):
    profile_picture = forms.ImageField(label='Profile Picture', required=False)

    def clean_image(self):
        profile_picture = self.cleaned_data['profile_picture']
        if profile_picture.size > 2000000:
            raise ValidationError('Image file is too large (max 2MB).')
        if not profile_picture.content_type in ['image/jpeg', 'image/png']:
            raise ValidationError('Image file must be JPEG or PNG.')
        return profile_picture
    
class QueryResponseForm(forms.ModelForm):
    response = forms.CharField(
        label='Response to for Query',
        widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Enter Your Response to the query here'}),
    )
    """Form for query response"""
    class Meta:
        model = Query
        fields = ['response',]

staff/api/views.py
from rest_framework import generics, status
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticated
from rest_framework.parsers import FileUploadParser

from ..models import Staff, Query, UserProfile
from .serializers import StaffSerializer, QuerySerializer, UserProfileSerializer
from .permissions import IsPartOfOrg


class StaffListView(generics.ListAPIView):
    serializer_class = StaffSerializer
    permission_classes = [IsAuthenticated, IsPartOfOrg]

    def get_queryset(self):
        return Staff.objects.filter(organization=self.request.user.staff.organization)
    

class StaffUserProfileDetailAPIView(generics.RetrieveAPIView):
    serializer_class = UserProfileSerializer
    permission_classes = [IsAuthenticated, IsPartOfOrg]
    
    def get_object(self):
        return self.request.user.staff.userprofile
    

class StaffPictureUploadAPIView(generics.UpdateAPIView):
    serializer_class = StaffSerializer
    permission_classes = [IsAuthenticated, IsPartOfOrg]
    parser_class = (FileUploadParser,)

    def get_object(self):
        return self.request.user.staff

    def put(self, request, *args, **kwargs):
        instance = self.get_object()
        if 'profile_picture' not in request.data:
            return Response({'error': 'No file uploaded.'}, status=status.HTTP_400_BAD_REQUEST)
        
        file = request.data['profile_picture']
        UserProfile.objects.get_or_create(staff_profile=instance) 
        instance.userprofile.profile_picture.save(file.name, file, save=True)
        serializer = self.get_serializer(instance)
        return Response(serializer.data)
    

class CurrentStaffQueriesListAPIView(generics.ListAPIView):
    serializer_class = QuerySerializer
    permission_classes = [IsAuthenticated, IsPartOfOrg]

    def get_queryset(self):
        return self.request.user.staff.queries.all()
    

class QueryUpdateResponse(generics.UpdateAPIView):
    serializer_class = QuerySerializer
    permission_classes = [IsAuthenticated, IsPartOfOrg]

    def patch(self, request, *args, **kwargs):
        instance = self.get_object()
        instance.response = request.data.get('response', instance.response)
        instance.is_responded = True
        instance.save(update_fields=['response', 'is_responded'])
        serializer = self.get_serializer(instance)
        return Response(serializer.data, status=status.HTTP_200_OK)

    def get_queryset(self):
        return self.request.user.staff.queries.all()

staff/views.py
from typing import Any, Dict
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import FormView, ListView, TemplateView, UpdateView

from .forms import ProfilePictureForm, QueryResponseForm
from .models import Query, Staff, UserProfile
from accounts.models import User

# Create your views here.
class StaffDashboardView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = Staff
    template_name = 'staff/dashboard.html'
    context_object_name = 'staff_list'
    raise_exception = True

    def get_queryset(self):
        return Staff.objects.filter(organization=self.request.user.staff.organization)
    
    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context_data = super().get_context_data(**kwargs)
        active_query_count = self.request.user.staff.queries.filter(is_responded=False).count()
        context_data["active_query_count"] = active_query_count
        return context_data
    
    def has_permission(self):
        org_slug = self.kwargs['org_slug']
        try:
            self.request.user.staff
            return self.request.user.staff.organization.slug == org_slug and not self.request.user.is_staff
        except User.staff.RelatedObjectDoesNotExist:
            return False
    

class StaffProfileView(LoginRequiredMixin,PermissionRequiredMixin, TemplateView):
    model = UserProfile
    template_name = 'staff/staff_profile.html'

    def has_permission(self):
        org_slug = self.kwargs['org_slug']
        try:
            self.request.user.staff
            return self.request.user.staff.organization.slug == org_slug and not self.request.user.is_staff
        except User.staff.RelatedObjectDoesNotExist:
            return False
    

class UploadProfilePictureView(LoginRequiredMixin, PermissionRequiredMixin, FormView):
    template_name = 'staff/upload_profile_picture.html'
    form_class = ProfilePictureForm

    def form_valid(self, form):
        profile_picture = form.cleaned_data['profile_picture']
        # profile_picture = self.request.FILES.get('profile_picture')
        staff = self.request.user.staff
        UserProfile.objects.get_or_create(staff_profile=staff) 
        staff.userprofile.profile_picture = profile_picture
        staff.userprofile.save()
        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse_lazy(
            "staff:staff_profile",
            kwargs={"org_slug": self.request.user.staff.organization.slug}
        )
    
    def has_permission(self):
        org_slug = self.kwargs['org_slug']
        try:
            self.request.user.staff
            return self.request.user.staff.organization.slug == org_slug and not self.request.user.is_staff
        except User.staff.RelatedObjectDoesNotExist:
            return False
    

class StaffQueryListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = Query
    template_name = "staff/query_list.html"
    context_object_name = 'query_list'

    def get_queryset(self):
        queryset = self.request.user.staff.queries.all()
        return queryset
        
    def has_permission(self):
        org_slug = self.kwargs['org_slug']
        try:
            self.request.user.staff
            return self.request.user.staff.organization.slug == org_slug and not self.request.user.is_staff
        except User.staff.RelatedObjectDoesNotExist:
            return False
    

class StaffQueryResponseView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Query
    form_class = QueryResponseForm
    template_name = "staff/query_form.html"

    def form_valid(self, form):
        query = form.save(commit=False)
        query.is_responded = True  # Set is_responded to True
        query.save()
        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse_lazy(
            "staff:query_list",
            kwargs={"org_slug": self.request.user.staff.organization.slug}
        )
        
    def has_permission(self):
        org_slug = self.kwargs['org_slug']
        try:
            self.request.user.staff
            return self.request.user.staff.organization.slug == org_slug and not self.request.user.is_staff
        except User.staff.RelatedObjectDoesNotExist:
            return False

staff/templates/staff/dashboard.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="content-wrapper">

    <div class="row">
      <div class="col-md-12 grid-margin">
        <div class="row">
          <div class="col-12 col-xl-8 mb-4 mb-xl-0">
            <h3 class="font-weight-bold">Welcome to the Staff Dashboard, {{ user.staff.first_name }}</h3>
          </div>
        </div>
      </div>
    </div>

    <div class="row">
        <div class="col-md-6 grid-margin stretch-card">
            <div class="card card-tale">
              <div class="card-body d-flex justify-content-center align-items-center">
                <h2 class=" mb-2 display1"> <a style="color: inherit;" href="{% url 'staff:staff_profile' org_slug=user.staff.organization.slug %}">View Profile</a></h2>
              </div>
            </div>
        </div> 
        <div class="col-md-6 grid-margin stretch-card">
            <div class="card card-tale">
              <div class="card-body d-flex justify-content-center align-items-center">
                <h2 class=" mb-2 display1"> <a style="color: inherit;" href="{% url 'staff:query_list' org_slug=user.staff.organization.slug %}">View Queries({{ active_query_count }})</a></h2>
              </div>
            </div>
        </div>     
    </div>


    <div class="row">
      <div class="col-md grid-margin stretch-card">
        <div class="card">
          <div class="card-body">
            <p class="card-title mb-0">All Staff</p>
            <div class="table-responsive">
              <table class="table table-striped table-hover table-borderless">
                <thead>
                  <tr>
                    <th>Last Name</th>
                    <th>First Name</th>
                    <th>Work Email</th>
                    <th>Phone</th>
                    <th>Job Title</th>
                    <th>Department</th>
                    <th>Status</th>

                  </tr>  
                </thead>
                <tbody>
                  {% for staff in staff_list %}
                    <tr>
                      <td> {{ staff.last_name }} </td>
                      <td> {{ staff.first_name }} </td>
                      <td> <span id="email-{{ staff.pk }}">{{ staff.work_email }}</span> </td>
                      <td> <span id="phone-{{ staff.pk }}">{{ staff.phone_number }}</span></td>
                      <td> {{ staff.job_title.role }} </td>
                      <td> {{ staff.dept.name }} </td>
                      <td class="font-weight-medium"><div 
                        class="badge {% if staff.staff_status == "Active" %}
                        badge-success
                        {% elif staff.staff_status == "Exited" %}
                        badge-danger
                        {% elif staff.staff_status == "Suspended" %}
                        badge-warning
                        {% else %}
                        badge-info
                        {% endif %}">
                        {{ staff.staff_status }}</div></td>
                    </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>

  </div>

  <script>
    function copyToClipboard(text) {
      // Create a temporary input element
      const input = document.createElement('input');
      input.setAttribute('value', text);
      document.body.appendChild(input);
  
      // Select the text field
      input.select();
      input.setSelectionRange(0, 99999); // For mobile devices
  
      // Copy the text inside the text field
      document.execCommand('copy');
  
      // Remove the temporary input element
      document.body.removeChild(input);
    }
  
    // Add event listeners to email and phone number cells
    const emailCells = document.querySelectorAll('.table td:nth-child(3)');
    const phoneCells = document.querySelectorAll('.table td:nth-child(4)');
  
    emailCells.forEach(cell => {
      const email = cell.textContent;
      cell.innerHTML += ` <a href="#" class="copy-link" onclick="copyToClipboard('${email}')"><i class="mdi mdi-content-copy"></i></a>`;
    });
  
    phoneCells.forEach(cell => {
      const phone = cell.textContent;
      cell.innerHTML += ` <a href="#" class="copy-link" onclick="copyToClipboard('${phone}')"><i class="mdi mdi-content-copy"></i></a>`;
    });
  </script>
  

{% endblock %}

staff/templates/staff/query_form.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="col-12 grid-margin stretch-card">
    <div class="card">
      <div class="card-body">
            <h4 class="card-title">Query Response Form</h4>
            <p class="card-description">
                Respond to this query to dispute it
            </p>
            <form method="POST" class="forms-sample">

                {% csrf_token %}
                {% if form.errors %}
                  <div class="alert alert-danger">
                    <strong>Oops! There was an error:</strong>
                    <ul>
                      {% for field, error in form.errors.items %}
                        {% if field != NON_FIELD_ERRORS %}
                          <li>{{ field }}: {{ error }}</li>
                        {% else %}
                          <li>{{ error }}</li>
                        {% endif %}
                      {% endfor %}
                    </ul>
                  </div>
                {% endif %}

                <div class="form-group">
                    {{ form.response.label_tag }}
                    {{ form.response }}
                </div>
                
                <div class="mt-3">
                    <input class="btn btn-primary mr-2" value="Submit" type="submit">
                </div>

            </form>
        </div>
    </div>
</div>


{% endblock %}

staff/templates/staff/query_list.html
{% extends 'base.html' %}

{% block content %}

<h1>All Queries</h1>

<ul>
    {% for query in query_list %}

    <li>
        <p><strong>Query Reason:</strong> {{ query.reason }}</p>
        {% if not query.is_responded %}
        <p><a href="{% url 'staff:query_response' org_slug=user.staff.organization.slug pk=query.pk %}">Dispute Query</a></p>
        {% else %}
        <p><strong>Query Response:</strong> {{ query.response }}</p>
        <p class="text-danger">Resolved</p>
        {% endif %}

    </li>
    
    {% empty %}
        <p>No Queries found.</p>
    {% endfor %}

</ul>

{% endblock%}

staff/templates/staff/staff_profile.html
{% extends 'base.html' %}

{% block  content %}

<h1>
    {{ user.staff.first_name }} {{ user.staff.last_name }}
</h1>
<h2>
    <small class="text-muted">
        {{ user.staff.dept.name }} : {{ user.staff.job_title.role }}
  </small>
</h2>

<div class="card-header bg-transparent">
    {% if user.staff.userprofile.profile_picture %}
    <img class="profile_img" src="{{ user.staff.userprofile.profile_picture.url }}" alt="staff photo">
    {% else %}
    <img class="profile_img" src="" alt="staff photo">
    {% endif %}
</div>
<p><a class="btn btn-primary mt-3" href="{% url "staff:upload_photo" org_slug=user.staff.organization.slug %}">Upload New Image</a></p>

<p> <strong>Gender:</strong> {{ user.staff.gender }}</p>
<p> <strong>Personal Email:</strong> {{ user.staff.personal_email }}</p>
<p> <strong>Work Email:</strong> {{ user.staff.work_email }}</p>
<p> <strong>Username:</strong> {{ user.staff.username }}</p>
<p> <strong>Phone number:</strong> {{ user.staff.phone_number }}</p>
<p> <strong>Date of Birth:</strong> {{ user.staff.date_of_birth }}</p>
<p> <strong>State of Origin:</strong> {{ user.staff.state_of_origin }}</p>
<p> <strong>Staff Status:</strong> {{ user.staff.staff_status }}</p>


{% endblock %}

staff/templates/staff/upload_profile_picture.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="content-wrapper" style="margin-top: 25px;">
    
    <div class="col-12 grid-margin stretch-card">
        <div class="card">
        <div class="card-body">
                <h4 class="card-title">Upload Profile Picture </h4>
                <p class="card-description">
                    Upload New Profile Picture
                </p>
                {% if messages %}
                    <ul class="messages">
                    {% for message in messages %}
                        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                    {% endfor %}
                    </ul>
                {% endif %}
                <form method="POST" enctype="multipart/form-data" class="forms-sample">

                    {% csrf_token %}
                    {% if form.errors %}
                    <div class="alert alert-danger">
                        <strong>Oops! There was an error:</strong>
                        <ul>
                        {% for field, error in form.errors.items %}
                            {% if field != NON_FIELD_ERRORS %}
                            <li>{{ field }}: {{ error }}</li>
                            {% else %}
                            <li>{{ error }}</li>
                            {% endif %}
                        {% endfor %}
                        </ul>
                    </div>
                    {% endif %}

                    <div class="form-group">
                        {{ form.profile_picture}}
                    </div>

                    <div class="mt-3">
                        <button class="btn btn-primary btn-icon-text mr-2" type="submit"><i class="ti-upload btn-icon-prepend"></i>Upload</button>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}